# Copyright 2026 VibeSpace LLC
# Licensed under the Apache License, Version 2.0

"""
Pydantic v2 schemas for the Discovery Engine.

These are the data contracts between agents — separate from ORM models.
Aligns with NUTRIENTS.md DATA_CONTRACTS.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional, Union
from uuid import UUID

from pydantic import BaseModel, Field, ConfigDict, computed_field


# ─── Candidate ────────────────────────────────────────────────────────────────


class CandidateSchema(BaseModel):
    """Full candidate profile used as input to the Discovery Engine."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    name: str
    email: str
    resume_text: str
    linkedin_url: Optional[str] = None
    github_url: Optional[str] = None
    personal_context: Optional[str] = None
    target_locations: list[str] = Field(default_factory=list)
    remote_preference: str = "flexible"
    min_compensation: Optional[int] = None
    excluded_companies: list[str] = Field(default_factory=list)
    excluded_industries: list[str] = Field(default_factory=list)
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


# ─── Identity Profile ─────────────────────────────────────────────────────────


class IdentityProfileSchema(BaseModel):
    """
    Multi-dimensional identity model for a candidate.

    Generated by IdentityProfiler — the foundation of the entire discovery run.
    Cached in Redis for 24h.

    Matches NUTRIENTS.md DATA_CONTRACTS.IdentityProfile.
    """

    model_config = ConfigDict(from_attributes=True)

    archetypes: list[str] = Field(default_factory=list)
    archetype_tags: list[str] = Field(default_factory=list)  # Alias for agents
    leadership_level: str = Field(
        default="IC",
        description="IC | Lead | Manager | Director | VP | C-Level",
    )
    technical_skills: Union[dict[str, int], list[str]] = Field(default_factory=dict)
    soft_skills: list[str] = Field(default_factory=list)
    domain_expertise: list[str] = Field(default_factory=list)
    industry_experience: list[str] = Field(default_factory=list)
    notable_achievements: list[str] = Field(default_factory=list)
    career_trajectory: str = ""
    ideal_role_description: str = ""
    creative_layer: list[str] = Field(default_factory=list)
    signals: dict[str, str] = Field(default_factory=dict)


# Alias for backward compatibility
IdentityProfile = IdentityProfileSchema


# ─── Search Manifest ─────────────────────────────────────────────────────────


class SearchManifestSchema(BaseModel):
    """
    Search instructions derived from an IdentityProfile.

    Matches NUTRIENTS.md DATA_CONTRACTS.SearchManifest.
    """

    model_config = ConfigDict(from_attributes=True)

    target_titles: list[str] = Field(default_factory=list)
    keywords: list[str] = Field(default_factory=list)
    excluded_titles: list[str] = Field(default_factory=list)
    excluded_companies: list[str] = Field(default_factory=list)
    excluded_industries: list[str] = Field(default_factory=list)
    location_filters: list[str] = Field(default_factory=list)
    remote_preference: str = "flexible"
    min_compensation: Optional[int] = None


# ─── Discovered Job ───────────────────────────────────────────────────────────


class DiscoveredJobSchema(BaseModel):
    """
    Raw job data from a crawl — before scoring.

    Matches NUTRIENTS.md DATA_CONTRACTS.DiscoveredJob.
    """

    model_config = ConfigDict(from_attributes=True)

    id: Optional[UUID] = None
    source: str
    source_id: str
    title: str
    company: str
    location: Optional[str] = None
    description: Optional[str] = None
    url: str
    posted_at: Optional[datetime] = None
    salary_min: Optional[int] = None
    salary_max: Optional[int] = None
    remote: bool = False
    crawled_at: Optional[datetime] = None


# ─── Score Breakdown ─────────────────────────────────────────────────────────


class ScoreBreakdown(BaseModel):
    """
    Dimension-level score breakdown (0-100 per dimension).

    Matches NUTRIENTS.md DATA_CONTRACTS.ScoreBreakdown.
    """

    model_config = ConfigDict(from_attributes=True)

    technical_match: int = Field(ge=0, le=100)
    level_match: int = Field(ge=0, le=100)
    culture_match: int = Field(ge=0, le=100)
    industry_match: int = Field(ge=0, le=100)
    growth_potential: int = Field(ge=0, le=100)
    compensation_match: int = Field(ge=0, le=100)

    @computed_field
    @property
    def composite(self) -> int:
        """
        Weighted composite score.

        Weights (sum to 100%):
          - technical_match: 30%
          - level_match: 20%
          - culture_match: 15%
          - industry_match: 15%
          - growth_potential: 10%
          - compensation_match: 10%
        """
        return int(
            self.technical_match * 0.30
            + self.level_match * 0.20
            + self.culture_match * 0.15
            + self.industry_match * 0.15
            + self.growth_potential * 0.10
            + self.compensation_match * 0.10
        )


# ─── Scored Job ───────────────────────────────────────────────────────────────


class ScoredJobSchema(BaseModel):
    """
    A discovered job with full scoring breakdown and reasoning.

    Matches NUTRIENTS.md DATA_CONTRACTS.ScoredJob.
    """

    model_config = ConfigDict(from_attributes=True)

    id: Optional[UUID] = None
    discovered_job_id: UUID
    candidate_id: UUID
    score_breakdown: ScoreBreakdown
    composite_score: int = Field(ge=0, le=100)
    is_hot: bool = False
    reasoning: str
    scored_at: Optional[datetime] = None

    # Denormalized job fields for digest display
    title: str = ""
    company: str = ""
    location: Optional[str] = None
    url: str = ""


# ─── Daily Digest ─────────────────────────────────────────────────────────────


class DailyDigestSchema(BaseModel):
    """
    Full daily digest — persisted to DB and published to Redis.

    Matches NUTRIENTS.md DATA_CONTRACTS.DailyDigest.
    """

    model_config = ConfigDict(from_attributes=True)

    id: Optional[UUID] = None
    candidate_id: UUID
    run_date: str = Field(description="ISO date: YYYY-MM-DD")
    top_picks: list[ScoredJobSchema] = Field(default_factory=list)
    hot_picks: list[ScoredJobSchema] = Field(default_factory=list)
    new_companies: list[str] = Field(default_factory=list)
    total_jobs_discovered: int = 0
    total_jobs_scored: int = 0
    created_at: Optional[datetime] = None
