# Copyright 2026 VibeSpace LLC
# Licensed under the Apache License, Version 2.0

"""
Pydantic v2 schemas for the Discovery Engine.

These are the data contracts between agents — separate from ORM models.
"""

from __future__ import annotations
from datetime import datetime
from typing import Optional
from uuid import UUID
from pydantic import BaseModel, Field, EmailStr


# ─── Candidate ────────────────────────────────────────────────────────────────

class CandidateSchema(BaseModel):
    """Full candidate profile used as input to the Discovery Engine."""

    id: UUID
    name: str
    email: str
    resume_text: str
    linkedin_url: Optional[str] = None
    github_url: Optional[str] = None
    personal_context: str = ""
    target_locations: list[str] = Field(default_factory=list)
    remote_preference: str = "flexible"
    min_compensation: Optional[int] = None
    excluded_companies: list[str] = Field(default_factory=list)
    excluded_industries: list[str] = Field(default_factory=list)

    model_config = {"from_attributes": True}


# ─── Identity Profile ─────────────────────────────────────────────────────────

class IdentityProfile(BaseModel):
    """
    Multi-dimensional identity model for a candidate.

    Generated by IdentityProfiler — the foundation of the entire discovery run.
    Cached in Redis for 24h.
    """

    candidate_id: UUID
    technical_skills: dict[str, int] = Field(
        description="Skill → proficiency score 0–100, weighted by recency"
    )
    domain_expertise: list[str] = Field(
        description="Industries and problem spaces: fintech, web3, ai, music, creator-economy, etc."
    )
    leadership_level: str = Field(
        description="ic | lead | staff | principal | founder | exec"
    )
    archetype_tags: list[str] = Field(
        description="Human-readable identity descriptors: technical-founder, ai-builder, creative-technologist"
    )
    role_expansion: list[str] = Field(
        description="15–20 non-obvious role archetypes this candidate should target"
    )
    culture_signals: dict[str, str] = Field(
        description="Preferences: startup_vs_enterprise, remote_preference, mission_vs_comp"
    )
    compensation_band: dict[str, int] = Field(
        description="min/max estimated target comp in USD"
    )
    creative_layer: list[str] = Field(
        default_factory=list,
        description="Non-technical identity: music, art, entrepreneurship — used for culture matching"
    )
    generated_at: datetime = Field(default_factory=datetime.utcnow)


# ─── Archetype Manifest ───────────────────────────────────────────────────────

class TargetCompanyProfile(BaseModel):
    """A profile of the type of company to watch."""

    industries: list[str]
    stages: list[str] = Field(description="seed, series-a, series-b, growth, public")
    size_range: str = Field(description="e.g. '10-200', '200-2000'")
    tech_signals: list[str] = Field(description="Technologies that signal a good fit")
    culture_signals: list[str]


class ArchetypeManifest(BaseModel):
    """
    Search instructions derived from an IdentityProfile.

    The crawler uses this as its target list.
    """

    candidate_id: UUID
    target_titles: list[str] = Field(description="Specific job titles to search")
    title_variants: dict[str, list[str]] = Field(
        description="Archetype → list of title search variants"
    )
    target_company_profile: TargetCompanyProfile
    target_industries: list[str] = Field(description="Industries ranked by fit")
    keywords: list[str] = Field(description="Search keyword combinations")
    exclusions: dict[str, list[str]] = Field(
        description="titles and companies to skip: {titles: [...], companies: [...]}"
    )
    generated_at: datetime = Field(default_factory=datetime.utcnow)


# ─── Discovered Job ───────────────────────────────────────────────────────────

class DiscoveredJobSchema(BaseModel):
    """Raw job data from a crawl — before scoring."""

    id: Optional[UUID] = None
    candidate_id: UUID
    title: str
    company: str
    location: Optional[str] = None
    url: str
    url_hash: str
    description: Optional[str] = None
    source: Optional[str] = None
    posted_date: Optional[datetime] = None
    status: str = "DISCOVERED"

    model_config = {"from_attributes": True}


# ─── Scored Job ───────────────────────────────────────────────────────────────

class ScoreBreakdown(BaseModel):
    """Dimension-level score breakdown."""

    technical_match: int = Field(ge=0, le=100)
    level_match: int = Field(ge=0, le=100)
    culture_match: int = Field(ge=0, le=100)
    industry_match: int = Field(ge=0, le=100)
    growth_potential: int = Field(ge=0, le=100)
    compensation_match: int = Field(ge=0, le=100)

    @property
    def composite(self) -> int:
        """Weighted composite score."""
        return int(
            self.technical_match * 0.30
            + self.level_match * 0.20
            + self.culture_match * 0.15
            + self.industry_match * 0.15
            + self.growth_potential * 0.10
            + self.compensation_match * 0.10
        )


class ScoredJobSchema(BaseModel):
    """A discovered job with full scoring breakdown and reasoning."""

    job: DiscoveredJobSchema
    scores: ScoreBreakdown
    composite_score: int = Field(ge=0, le=100)
    reasoning: str = Field(description="2-sentence human-readable reasoning for the score")
    is_hot: bool = False

    model_config = {"from_attributes": True}


# ─── Daily Digest ─────────────────────────────────────────────────────────────

class DigestJobPreview(BaseModel):
    """Lightweight job preview for the digest list."""

    job_id: UUID
    title: str
    company: str
    location: Optional[str]
    url: str
    composite_score: int
    is_hot: bool
    reasoning: str


class DailyDigestSchema(BaseModel):
    """Full daily digest — persisted to DB and published to Redis."""

    candidate_id: UUID
    run_date: str = Field(description="ISO date: YYYY-MM-DD")
    total_discovered: int
    total_scored: int
    top_picks: list[DigestJobPreview]
    hot_picks: list[DigestJobPreview]
    new_companies: list[str]
    digest_summary: str = Field(description="Claude-generated 3-sentence narrative")
