# Copyright 2026 VibeSpace LLC
# Licensed under the Apache License, Version 2.0

"""
Pydantic v2 schemas for the Application Engine.

These are the data contracts between application agents — separate from ORM models.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional, Union
from uuid import UUID

from pydantic import BaseModel, Field, ConfigDict


# ─── Parsed JD ────────────────────────────────────────────────────────────────


class ParsedJDSchema(BaseModel):
    """
    Deep-parsed job description — every signal needed for tailoring the application.

    Generated by JDParser. Cached in PostgreSQL — reused if job is re-processed.
    """

    model_config = ConfigDict(from_attributes=True)

    id: Optional[UUID] = None
    job_id: UUID
    required_skills: list[str] = Field(default_factory=list)
    preferred_skills: list[str] = Field(default_factory=list)
    seniority_level: str = "senior"
    team_context: Optional[str] = None
    key_responsibilities: list[str] = Field(default_factory=list)
    culture_signals: dict[str, str] = Field(default_factory=dict)
    tech_stack: list[str] = Field(default_factory=list)
    pain_points: Optional[str] = None
    tone: str = "professional"
    comp_mentioned: Optional[str] = None
    red_flags: list[str] = Field(default_factory=list)
    application_instructions: Optional[str] = None
    parsed_at: Optional[datetime] = None


# ─── Tailored Resume ──────────────────────────────────────────────────────────


class TailoredResumeSchema(BaseModel):
    """
    Rewritten resume tailored for a specific role.

    Never fabricates experience — rewrites framing, ordering, and emphasis.
    """

    model_config = ConfigDict(from_attributes=True)

    id: Optional[UUID] = None
    pipeline_id: Optional[UUID] = None
    job_id: Optional[UUID] = None
    candidate_id: Optional[UUID] = None
    original_text: str = ""
    tailored_text: str = ""
    summary: str = ""
    full_text: str = ""
    change_log: Union[str, list[str]] = ""
    gap_analysis: Optional[str] = None
    version: int = 1
    pdf_path: Optional[str] = None
    created_at: Optional[datetime] = None


# ─── Company Intel ────────────────────────────────────────────────────────────


class CompanyIntelSchema(BaseModel):
    """
    Synthesized company research for outreach composition.

    Cached 7 days — don't re-scrape the same company within a week.
    """

    model_config = ConfigDict(from_attributes=True)

    id: Optional[UUID] = None
    pipeline_id: Optional[UUID] = None
    company_name: str
    domain: Optional[str] = None
    about: Optional[str] = None
    recent_news: Optional[str] = None
    tech_stack: list[str] = Field(default_factory=list)
    engineering_culture: Optional[str] = None
    glassdoor_signals: Optional[str] = None
    growth_stage: Optional[str] = None
    team_size: Optional[str] = None
    notable_facts: Optional[str] = None
    cache_age: Optional[datetime] = None
    researched_at: Optional[datetime] = None


# ─── Contact ──────────────────────────────────────────────────────────────────


class ContactSchema(BaseModel):
    """
    The right person to send the cold outreach to.

    Confidence levels: HIGH = verified email; MEDIUM = pattern-matched; LOW = generic fallback.
    """

    model_config = ConfigDict(from_attributes=True)

    id: Optional[UUID] = None
    pipeline_id: Optional[UUID] = None
    company_intel_id: Optional[UUID] = None
    name: Optional[str] = None
    title: Optional[str] = None
    email: Optional[str] = None
    linkedin_url: Optional[str] = None
    confidence: str = "LOW"  # HIGH | MEDIUM | LOW
    fallback_email: Optional[str] = None
    source: Optional[str] = None
    found_at: Optional[datetime] = None


# ─── Outreach Email ───────────────────────────────────────────────────────────


class OutreachEmailSchema(BaseModel):
    """
    A cold email that doesn't read like a cold email.

    Stays in DRAFT status until approved in the Review Dashboard.
    Max 150–200 words. Grounded in real company context.
    """

    model_config = ConfigDict(from_attributes=True)

    id: Optional[UUID] = None
    pipeline_id: Optional[UUID] = None
    job_id: Optional[UUID] = None
    candidate_id: Optional[UUID] = None
    to: Optional[str] = None
    subject: str = ""
    subject_lines: list[str] = Field(
        default_factory=list,
        description="3 subject line variants shown in Review Dashboard",
    )
    subject_variants: list[str] = Field(default_factory=list)
    body: str = Field(default="", description="Email body — 150–200 words max")
    tone_used: Optional[str] = None
    hook_used: Optional[str] = None
    status: str = "DRAFT"  # DRAFT | SENT | BOUNCED | REPLIED
    created_at: Optional[datetime] = None


# ─── Application Result ───────────────────────────────────────────────────────


class ApplicationResultSchema(BaseModel):
    """
    Result of an auto-apply submission attempt.

    Status can be: SUBMITTED, FAILED, REQUIRES_MANUAL
    """

    model_config = ConfigDict(from_attributes=True)

    pipeline_id: UUID
    job_id: UUID
    status: str  # SUBMITTED | FAILED | REQUIRES_MANUAL
    confirmation_number: Optional[str] = None
    screenshot_path: Optional[str] = None
    fields_completed: list[str] = Field(default_factory=list)
    error: Optional[str] = None
    fallback_url: Optional[str] = None


# ─── Application Pipeline ─────────────────────────────────────────────────────


class ApplicationPipelineSchema(BaseModel):
    """
    Full pipeline state for a single approved job application.

    Status flow:
      QUEUED → PARSING → TAILORING → RESEARCHING → COMPOSING →
      AWAITING_REVIEW → APPROVED/REJECTED → SUBMITTED → SENT → TRACKED
    """

    model_config = ConfigDict(from_attributes=True)

    id: Optional[UUID] = None
    candidate_id: UUID
    job_id: UUID
    status: str = "QUEUED"
    parsed_jd: Optional[ParsedJDSchema] = None
    tailored_resume: Optional[TailoredResumeSchema] = None
    company_intel: Optional[CompanyIntelSchema] = None
    contact: Optional[ContactSchema] = None
    outreach_email: Optional[OutreachEmailSchema] = None
    approval_timestamp: Optional[datetime] = None
    submitted_at: Optional[datetime] = None
    screenshots: list[str] = Field(default_factory=list)
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


# ─── CRM Event ────────────────────────────────────────────────────────────────


class CRMEventSchema(BaseModel):
    """An immutable timeline event in the application journey."""

    model_config = ConfigDict(from_attributes=True)

    id: Optional[UUID] = None
    pipeline_id: UUID
    event_type: str = Field(
        default="",
        description="JD_PARSED | RESUME_TAILORED | COMPANY_RESEARCHED | CONTACT_FOUND | "
        "EMAIL_DRAFTED | SUBMITTED | PIPELINE_FAILED | APPROVED | REJECTED",
    )
    payload: Optional[dict] = Field(default_factory=dict)
    created_at: Optional[datetime] = None
