# Copyright 2026 VibeSpace LLC
# Licensed under the Apache License, Version 2.0

"""
Pydantic v2 schemas for the Application Engine.

These are the data contracts between application agents — separate from ORM models.
"""

from __future__ import annotations
from datetime import datetime
from typing import Optional
from uuid import UUID
from pydantic import BaseModel, Field


# ─── Parsed JD ────────────────────────────────────────────────────────────────

class ParsedJDSchema(BaseModel):
    """
    Deep-parsed job description — every signal needed for tailoring the application.

    Generated by JDParser. Cached in PostgreSQL — reused if job is re-processed.
    """

    job_id: UUID
    required_skills: list[str] = Field(default_factory=list)
    preferred_skills: list[str] = Field(default_factory=list)
    seniority_level: str = "senior"
    team_context: Optional[str] = None
    key_responsibilities: list[str] = Field(default_factory=list)
    culture_signals: dict[str, str] = Field(default_factory=dict)
    tech_stack: list[str] = Field(default_factory=list)
    pain_points: Optional[str] = None
    tone: str = "professional"
    comp_mentioned: Optional[str] = None
    red_flags: list[str] = Field(default_factory=list)
    application_instructions: Optional[str] = None

    model_config = {"from_attributes": True}


# ─── Tailored Resume ──────────────────────────────────────────────────────────

class TailoredResumeSchema(BaseModel):
    """
    Rewritten resume tailored for a specific role.

    Never fabricates experience — rewrites framing, ordering, and emphasis.
    """

    job_id: UUID
    candidate_id: UUID
    summary: str = Field(description="Rewritten profile/summary targeting this role")
    full_text: str = Field(description="Complete resume text ready for PDF generation")
    change_log: str = Field(description="What changed from base resume and why — shown in Review Dashboard")
    pdf_path: Optional[str] = None
    version: int = 1

    model_config = {"from_attributes": True}


# ─── Company Intel ────────────────────────────────────────────────────────────

class CompanyIntelSchema(BaseModel):
    """
    Synthesized company research for outreach composition.

    Cached 7 days — don't re-scrape the same company within a week.
    """

    company_name: str
    domain: Optional[str] = None
    about: Optional[str] = None
    recent_news: Optional[str] = None
    tech_stack: list[str] = Field(default_factory=list)
    engineering_culture: Optional[str] = None
    glassdoor_signals: Optional[str] = None
    growth_stage: Optional[str] = None
    team_size: Optional[str] = None
    notable_facts: Optional[str] = Field(
        description="The hook — specific and real, used to open the outreach email"
    )
    cache_age: Optional[datetime] = None

    model_config = {"from_attributes": True}


# ─── Contact ──────────────────────────────────────────────────────────────────

class ContactSchema(BaseModel):
    """
    The right person to send the cold outreach to.

    Confidence levels: HIGH = verified email; MEDIUM = pattern-matched; LOW = generic fallback.
    """

    name: Optional[str] = None
    title: Optional[str] = None
    email: Optional[str] = None
    linkedin_url: Optional[str] = None
    confidence: str = "LOW"  # HIGH | MEDIUM | LOW
    source: Optional[str] = None
    fallback_email: Optional[str] = None


# ─── Outreach Email ───────────────────────────────────────────────────────────

class OutreachEmailSchema(BaseModel):
    """
    A cold email that doesn't read like a cold email.

    Stays in DRAFT status until approved in the Review Dashboard.
    Max 150–200 words. Grounded in real company context.
    """

    job_id: UUID
    candidate_id: UUID
    to: Optional[str] = None
    subject: str = Field(description="Primary subject line")
    subject_variants: list[str] = Field(
        default_factory=list,
        description="3 subject line variants shown in Review Dashboard"
    )
    body: str = Field(description="Email body — 150–200 words max")
    tone_used: str = "professional"
    hook_used: Optional[str] = Field(
        description="The specific company fact used as opening hook"
    )
    status: str = "DRAFT"


# ─── Application Result ───────────────────────────────────────────────────────

class ApplicationResultSchema(BaseModel):
    """
    Outcome of a form submission attempt.

    Never submitted without explicit Review Dashboard approval.
    """

    pipeline_id: UUID
    job_id: UUID
    status: str = Field(description="SUCCESS | FAILED | REQUIRES_MANUAL")
    confirmation_number: Optional[str] = None
    screenshot_path: Optional[str] = None
    fields_completed: list[str] = Field(default_factory=list)
    error: Optional[str] = None
    fallback_url: Optional[str] = Field(
        description="Direct link for manual submission if auto-apply fails"
    )


# ─── Application Pipeline ─────────────────────────────────────────────────────

class ApplicationPipelineSchema(BaseModel):
    """
    Full pipeline state for a single approved job application.

    Status flow:
      QUEUED → PARSING → TAILORING → RESEARCHING → COMPOSING →
      AWAITING_REVIEW → APPROVED/REJECTED → SUBMITTED → SENT → TRACKED
    """

    id: Optional[UUID] = None
    job_id: UUID
    candidate_id: UUID
    status: str = "QUEUED"
    current_step: Optional[str] = None
    parsed_jd: Optional[ParsedJDSchema] = None
    tailored_resume: Optional[TailoredResumeSchema] = None
    company_intel: Optional[CompanyIntelSchema] = None
    contact: Optional[ContactSchema] = None
    outreach_email: Optional[OutreachEmailSchema] = None
    result: Optional[ApplicationResultSchema] = None

    model_config = {"from_attributes": True}


# ─── CRM Event ────────────────────────────────────────────────────────────────

class CRMEventSchema(BaseModel):
    """An immutable timeline event in the application journey."""

    pipeline_id: UUID
    candidate_id: UUID
    job_id: UUID
    event_type: str = Field(description="APPLIED | EMAIL_SENT | EMAIL_OPENED | RESPONDED | INTERVIEW_SCHEDULED | OFFER_RECEIVED | REJECTED | PLACED")
    details: Optional[dict] = None
